### ISSUE TITLE
Erreur lors de la récupération des sessions depuis la MàJ

### ISSUE THREAD

**Issue by AntoineCrzt** [StephaneTy-Pro/OC-Mentors-AccountAddon#2]
La modal "traitement en cours" reste bloquée quand je fais check auto ou check à la main. 
Erreurs dans la console : 
![Bug](https://i.ibb.co/zPtZx8Y/Capture-d-cran-2021-01-18-11-44-52.png)

**Comment by StephaneTy-Pro** [comment]
Corrigé dans la nouvelle version 1.10.0003
